In [10]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('../3ytc61d048/data_3ytc61d048.csv')
last_50_columns = df.iloc[:, -50:]

In [8]:
def find_index_of_spikes(column, spike_value):
    index = column[column == spike_value].index
    return np.array(index) if not index.empty else np.nan

index_of_10 = last_50_columns.apply(find_index_of_spikes, args=(10.0,))
index_of_10.dropna(inplace = True)
max_len = max(map(len, index_of_10))
filled_lists = [list(filter(None, x)) + [np.nan] * (max_len - len(x)) for x in index_of_10]
res = np.array(filled_lists)

def find_tau_max(matrix, dt):
    count = 0
    sum_diff = 0
    for col in range(matrix.shape[1]):
        for i in range(len(matrix[:, col])):
            if not np.isnan(matrix[i][col]):
                for j in range(i+1, len(matrix[:, col])):
                    if not np.isnan(matrix[j][col]):
                        diff = abs(matrix[i][col] - matrix[j][col])
                        print(diff)
                        sum_diff += diff
                        count += 1
    return (sum_diff / count) * 2 * dt

result = find_tau_max(res, 0.1)
result

13.137388059701493

In [11]:
import layers
from utils import *
from tqdm import tqdm
import os

def main():
    # ---name for directory with results---
    random_dir_name = make_random_name(10)
    # ---creating dataframe for input spikes, membrane potential and output spikes---
    df = create_df(30)

    os.makedirs(random_dir_name)

    hidden_layer = layers.IntraConnectLayer(30, 10, 0.5, 0.1, f'../Hebb/{random_dir_name}')
    hidden_layer.from_edges()

    input_spikes = spike_generator(n=30, steps=10, version='1')

    print('Saved to folder: ', f'../Hebb/{random_dir_name}')

    for i in tqdm(range(len(input_spikes)), ascii=True, desc='forward'):
        out, mem = hidden_layer.intra_forward(input_spikes[i])
        df.loc[len(df.index)] = input_spikes[i].tolist() + mem + out.tolist()
        print(out)
        

    df_name = f'../Hebb/{random_dir_name}/data_.csv'
    df.to_csv(df_name, index=False)

    # ---draw heatmap and save image---
    plot_heatmap(df_name, random_dir_name)
    # ---draw graph and save image---
    hidden_layer.draw_graph()
    
main()

array([[ 28., 167., 311., 455.,  nan,  nan,  nan,  nan,  nan,  nan],
       [ 28., 167., 311., 455.,  nan,  nan,  nan,  nan,  nan,  nan],
       [ 39., 180., 323., 467.,  nan,  nan,  nan,  nan,  nan,  nan],
       [ 28., 167., 312., 456.,  nan,  nan,  nan,  nan,  nan,  nan],
       [ 33., 172., 323., 461.,  nan,  nan,  nan,  nan,  nan,  nan],
       [ 28., 167., 312., 455.,  nan,  nan,  nan,  nan,  nan,  nan],
       [ 33., 172., 325., 469.,  nan,  nan,  nan,  nan,  nan,  nan],
       [ 31., 170., 317., 461.,  nan,  nan,  nan,  nan,  nan,  nan],
       [ 28.,  39., 169., 311., 330., 458., 476.,  nan,  nan,  nan],
       [ 30., 170., 317., 461.,  nan,  nan,  nan,  nan,  nan,  nan],
       [ 30.,  39., 170., 317., 461.,  nan,  nan,  nan,  nan,  nan],
       [ 30.,  39., 170., 317., 461.,  nan,  nan,  nan,  nan,  nan],
       [ 28.,  33., 170., 312., 320., 458., 464.,  nan,  nan,  nan],
       [ 30.,  39., 170., 318., 462.,  nan,  nan,  nan,  nan,  nan],
       [ 28.,  34., 170., 313., 32

In [3]:
from utils import *
spikes = spike_generator(5, 100)
spikes.shape

100%|██████████| 100/100 [00:00<00:00, 6660.37it/s]


(100, 5)

In [5]:
output_spike = np.zeros([spikes.shape[0], spikes.shape[1]])
output_spike

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0.

In [15]:
list = [1,23, 4 ,5, 1, 1231, 23 ,12,31,23,123,12,3,1241,24 ,13,4,23,41,4]
np.reshape(list, (4, 5))

array([[   1,   23,    4,    5,    1],
       [1231,   23,   12,   31,   23],
       [ 123,   12,    3, 1241,   24],
       [  13,    4,   23,   41,    4]])

In [16]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])

combined_array = np.concatenate((arr1, arr2, arr3), axis=1)
print(combined_array)

[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]


In [17]:
arr1 

array([[1, 2],
       [3, 4]])